name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cmake_generator: "Unix Makefiles"
          - os: windows-latest
            cmake_generator: "Visual Studio 17 2022"
          - os: macos-latest
            cmake_generator: "Unix Makefiles"
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B ${{github.workspace}}/build 
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -G "${{matrix.cmake_generator}}"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Basic Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          ./Release/dircat.exe ..
        else
          ./dircat ..
        fi

    - name: Test Options
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          ./Release/dircat.exe .. --max-size 5 --no-recursive --ext cpp
        else
          ./dircat .. --max-size 5 --no-recursive --ext cpp
        fi